workspace:
  base: /node-app
  path: src/github.com/enobt/drone-cd-test

pipeline:
  frontend:
    image: node:8.1
    commands:
      - cd app
      - npm install
      - npm test

  deploy:
    image: drillster/drone-rsync
    hosts: [ "52.168.73.205" ]
    user: "rvansant"
    secrets: [ RSYNC_KEY ]
    target: /var/www/node-app
    include: [ "./app/index.js", "./app/package.json" ]
    exclude: [ "./app/test", "./app/node_modules", ".*", "*.yml" ]
    args: "--timeout=2400 --ignore-errors"
    script:
      - cd /var/www/node-app
      - git pull
      - sudo docker-compose up -d
