pipeline:
  frontend:
    image: node:8.1
    commands:
      - whoami
      - cd app
      - npm install
      - npm test

  deploy:
    image: drillster/drone-rsync
    hosts: [ "52.168.73.205" ]
    user: "rvansant"
    key: cat ~/.ssh/id_rsa
    target: /var/www/node-app
    include: [ "./DEPLOY" ]
    exclude: [ "./*.yml", "drone-data", ".*" ]
    args: "--timeout=2400 --ignore-errors"
    script:
      - cd /var/www/node-app
      - git pull
      - sudo docker-compose up -d