pipeline:
  frontend:
    image: node:8.1
    commands:
      - pwd
      - cd app
      - npm install
      - npm test

  deploy:
    image: drillster/drone-rsync
    hosts: [ "52.168.73.205" ]
    user: "rvansant"
    key: cat ~/.ssh/id_rsa
    target: /var/www
    include: [ "*" ]
    exclude: [ "./app/node_modules", "./app/test" ]
    script:
      - cd /var/www/app
      - docker-compose up -d