workspace:
  base: /node-app
  path: src/github.com/enobt/drone-cd-test

pipeline:
  node_app_backend:
    image: node:8.1
    commands:
      - cd app
      - npm install
      - npm test
    when:
      branch: master

  node_app_frontend:
    image: node:8.1
    commands:
      - cd ui
      - npm install
      - npm test
    when:
      branch: master

  deploy_backend:
    image: drillster/drone-rsync
    hosts: [ "52.168.149.156" ] #change hosts
    user: "rvansant"
    secrets: [ RSYNC_KEY ]
    target: /var/www/node-app
    include: [ "./api/bin", "./api/package.json", "./api/public", "./api/routes", "./api/views", "./api/package.json" ]
    exclude: [ "./api/test", "./api/node_modules", ".*", ".drone.yml" ]
    args: "--timeout=2400 --ignore-errors --omit-dir-times"
    script:
      - cd /var/www/node-app
      - sudo docker-compose build api mongo
      - sudo docker-compose up -d api 
    when:
      branch: master
      event: [ push ]

  deploy_frontend:
    image: drillster/drone-rsync
    hosts: [ "52.168.146.227" ]
    user: "rvansant"
    secrets: [ RSYNC_KEY ]
    target: /var/www/node-app
    include: [ "./ui/src", "./ui/package.json", "./ui/public" ]
    exclude: [ "./ui/test", "./ui/node_modules", ".*", ".drone.yml" ]
    args: "--timeout=2400 --ignore-errors --omit-dir-times"
    script:
      - cd /var/www/node-app
      - sudo docker-compose build ui
      - sudo docker-compose up -d ui
    when:
      branch: master
      event: [ push ]
