pipeline:
  frontend:
    image: node:8.1
    commands:
      - cd app
      - npm install
      - npm test

  deploy:
    image: drillster/drone-rsync
    hosts: [ "52.168.73.205" ]
    user: "rvansant"
    key: cat ~/.ssh/id_rsa
    target: /var/www/node-app
    include: [ "*" ]
    exclude: [ "*" ]
    args: "--timeout=2400"
    script:
      - cd /var/www/node-app
      - git pull
      - sudo docker-compose up -d