workspace:
  base: /node-app
  path: src/github.com/enobt/drone-cd-test

pipeline:
  node_app_staging:
    image: node:8.1
    commands:
      - cd app
      - npm install
      - npm test
    when:
      branch: develop

  node_app_production:
    image: node:8.1
    commands:
      - cd app
      - npm install
      - npm test
    when:
      branch: master

  deploy_staging:
    image: drillster/drone-rsync
    hosts: [ "52.168.73.205" ] #change hosts
    user: "rvansant"
    secrets: [ RSYNC_KEY ]
    target: /var/www/node-app
    include: [ "./app/index.js", "./app/package.json" ]
    exclude: [ "./app/test", "./app/node_modules", ".*", ".drone.yml" ]
    args: "--timeout=2400 --ignore-errors --omit-dir-times"
    script:
      - cd /var/www/node-app
      - sudo docker-compose build
      - sudo docker-compose up -d
    when:
      branch: develop

  deploy_production:
    image: drillster/drone-rsync
    hosts: [ "52.168.94.113" ]
    user: "rvansant"
    secrets: [ RSYNC_KEY ]
    target: /var/www/node-app
    include: [ "./app/index.js", "./app/package.json" ]
    exclude: [ "./app/test", "./app/node_modules", ".*", ".drone.yml" ]
    args: "--timeout=2400 --ignore-errors --omit-dir-times"
    script:
      - cd /var/www/node-app
      - sudo docker-compose build
      - sudo docker-compose up -d
    when:
      branch: master
