version: '2'
services:

  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - ./db-data:/data/db

  ui:
    build: ./ui
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/var/www/ui:rw

  api:
    build: ./api
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    volumes:
      - ./api:/var/www/api:rw


volumes:
  db-data:
